version: '3.7'

services:
  roscore_gazebo:
    # build:
    #     context: ~/simulation_ws/src/
    #     dockerfile: ./tortoisebot_ros1_docker/gazebo/Dockerfile
    # image: tortoisebot-ros1-gazebo:v1
    image: kkhadka343/kailash-cp22:tortoisebot-ros1-gazebo
    container_name: gazebo_container
    command: /bin/bash -c "source /home/ttbot/simulation_ws/devel/setup.bash && roslaunch tortoisebot_gazebo tortoisebot_playground.launch"
    stdin_open: true
    tty: true
    networks:
      - ros_network
    ports:
      - 11311:11311
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_HOSTNAME=gazebo_container
      - ROS_MASTER_URI=http://gazebo_container:11311
      - ROS_DISTRO=noetic
      - USERNAME=ttbot
      - CATKIN_WS=/home/ttbot/simulation_ws
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true

  waypoint_server:
    # build:
    #     context: ~/simulation_ws/src/
    #     dockerfile: ./tortoisebot_ros1_docker/waypoint_server/Dockerfile
    # image: tortoisebot-ros1-waypoints:v1
    image: kkhadka343/kailash-cp22:tortoisebot-ros1-waypoints
    container_name: waypoint_server_container
    stdin_open: true
    tty: true
    networks:
      - ros_network
    ports:
      - "9090:9090"  # rosbridge
      - 11315:11315  # web-video-server
    environment:
      - SLOT_ROSBRIDGE_PORT=9090
      - ROS_HOSTNAME=waypoint_server_container
      - ROS_MASTER_URI=http://gazebo_container:11311
      - ROS_DISTRO=noetic
      - USERNAME=ttbot
      - CATKIN_WS=/home/ttbot/simulation_ws
    privileged: true
    depends_on:
      - roscore_gazebo

  web_server:
    # build:
    #     context: ~/simulation_ws/src/
    #     dockerfile: ./tortoisebot_ros1_docker/web_server/Dockerfile
    # image: tortoisebot-ros1-webapp:v1
    image: kkhadka343/kailash-cp22:tortoisebot-ros1-webapp
    container_name: web_server_container
    command: "/entrypoint.sh"
    networks:
      - ros_network
    ports:
      - "8080:80"
    environment:
      - ROSBRIDGE_URL=ws://waypoint_server_container:9090
      - ROS_HOSTNAME=web_server_container
      - ROS_MASTER_URI=http://gazebo_container:11311
      - ROS_DISTRO=noetic
      - USERNAME=ttbot
      - WEBPAGE_WS=/home/ttbot/webpage_ws
    privileged: true
    depends_on:
      - roscore_gazebo
      - waypoint_server

networks:
  ros_network:
    driver: bridge
    name: checkpoint22_ros_network  # Explicitly name the network
